In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 

In [2]:
df = pd.read_csv('FootballDataset.csv')
df.shape[0]

6840

In [3]:
df.columns
df

Div       Date        HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  \
0     E0   19/08/00        Charlton        Man City     4     0   H     2   
1     E0   19/08/00         Chelsea        West Ham     4     2   H     1   
2     E0   19/08/00        Coventry   Middlesbrough     1     3   A     1   
3     E0   19/08/00           Derby     Southampton     2     2   D     1   
4     E0   19/08/00           Leeds         Everton     2     0   H     2   
5     E0   19/08/00       Leicester     Aston Villa     0     0   D     0   
6     E0   19/08/00       Liverpool        Bradford     1     0   H     0   
7     E0   19/08/00      Sunderland         Arsenal     1     0   H     0   
8     E0   19/08/00       Tottenham         Ipswich     3     1   H     2   
9     E0   20/08/00      Man United       Newcastle     2     0   H     1   
10    E0   21/08/00         Arsenal       Liverpool     2     0   H     1   
11    E0   22/08/00        Bradford         Chelsea     2     0   H     1   
12    E0   22/08/00         Ipswich      Man United     1     1   D     1   
13    E0   22/08/00   Middlesbrough       Tottenham     1     1   D     0   
14    E0   23/08/00         Everton        Charlton     3     0   H     0   
15    E0   23/08/00        Man City      Sunderland     4     2   H     2   
16    E0   23/08/00       Newcastle           Derby     3     2   H     1   
17    E0   23/08/00     Southampton        Coventry     1     2   A     0   
18    E0   23/08/00        West Ham       Leicester     0     1   A     0   
19    E0   26/08/00         Arsenal        Charlton     5     3   H     1   
20    E0   26/08/00        Bradford       Leicester     0     0   D     0   
21    E0   26/08/00         Everton           Derby     2     2   D     2   
22    E0   26/08/00         Ipswich      Sunderland     1     0   H     0   
23    E0   26/08/00        Man City        Coventry     1     2   A     0   
24    E0   26/08/00   Middlesbrough           Leeds     1     2   A     0   
25    E0   26/08/00       Newcastle       Tottenham     2     0   H     1   
26    E0   26/08/00     Southampton       Liverpool     3     3   D     0   
27    E0   26/08/00        West Ham      Man United     2     2   D     0   
28    E0   27/08/00     Aston Villa         Chelsea     1     1   D     1   
29    E0   5/9/2000           Leeds        Man City     1     2   A     0   
...   ..        ...             ...             ...   ...   ...  ..   ...   
6810  E0   28/04/18         Swansea         Chelsea     0     1   A     0   
6811  E0   29/04/18      Man United         Arsenal     2     1   H     1   
6812  E0   29/04/18        West Ham        Man City     1     4   A     1   
6813  E0   30/04/18       Tottenham         Watford     2     0   H     1   
6814  E0   4/5/2018        Brighton      Man United     1     0   H     0   
6815  E0   5/5/2018     Bournemouth         Swansea     1     0   H     1   
6816  E0   5/5/2018         Everton     Southampton     1     1   D     0   
6817  E0   5/5/2018       Leicester        West Ham     0     2   A     0   
6818  E0   5/5/2018           Stoke  Crystal Palace     1     2   A     1   
6819  E0   5/5/2018         Watford       Newcastle     2     1   H     2   
6820  E0   5/5/2018       West Brom       Tottenham     1     0   H     0   
6821  E0   6/5/2018         Arsenal         Burnley     5     0   H     2   
6822  E0   6/5/2018         Chelsea       Liverpool     1     0   H     1   
6823  E0   6/5/2018        Man City    Huddersfield     0     0   D     0   
6824  E0   8/5/2018         Swansea     Southampton     0     1   A     0   
6825  E0   9/5/2018         Chelsea    Huddersfield     1     1   D     0   
6826  E0   9/5/2018       Leicester         Arsenal     3     1   H     1   
6827  E0   9/5/2018        Man City        Brighton     3     1   H     2   
6828  E0   9/5/2018       Tottenham       Newcastle     1     0   H     0   
6829  E0  10/5/2018        West Ham      Man United     0     0   D     0   
6

In [4]:
df.drop(['HomeTeam', 'AwayTeam', 'Div', 'Date', 'FTHG', 'FTAG', 'HTHG',
         'HTAG', 'HTR', 'Attendance', 'Referee', 'HHW', 'AHW',
         'HC', 'AC', 'HO', 'AO', 'HY', 'AY', 'HR', 'AR', 'Unnamed: 28',
         'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31','Unnamed: 32', 
         'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
         'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 
         'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43','Unnamed: 44', 
         'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 
         'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 
         'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 
         'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 
         'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 
         'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67',
         'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70'],1, inplace=True)
display(df.head())

FTR  HS  AS  HST  AST  HF  AF
0   H  17   8   14    4  13  12
1   H  17  12   10    5  19  14
2   A   6  16    3    9  15  21
3   D   6  13    4    6  11  13
4   H  17  12    8    6  21  20

In [5]:
def transformResult(row):
    '''Converts results (H,A or D) into numeric values'''
    if(row.FTR == 'H'):
        return 1
    elif(row.FTR == 'A'):
        return -1
    else:
        return 0

In [6]:
df["FTR"] = df.apply(lambda row: transformResult(row),axis=1)
df.head()

FTR  HS  AS  HST  AST  HF  AF
0    1  17   8   14    4  13  12
1    1  17  12   10    5  19  14
2   -1   6  16    3    9  15  21
3    0   6  13    4    6  11  13
4    1  17  12    8    6  21  20

In [7]:
totalMatches = df.shape[0]
totalFeatures = df.shape[1] - 1
homeWins = len(df[df.FTR == 1])
draw = len(df[df.FTR == 0])
awayWins = len(df[df.FTR == -1])
homeRate = (float(homeWins) / (totalMatches)) * 100
drawRate = (float(draw) / (totalMatches)) * 100
awayRate = (float(awayWins) / (totalMatches)) * 100


print ("Total number of matches: ", totalMatches)
print ("Number of features: ", totalFeatures,'\n')
print ("Number of matches won by home team: ", homeWins)
print ("Win rate of home team: ", homeRate,'\n')
print ("Number of matches drawn: ", draw)
print ("Draw rate of the total matches: ", drawRate,'\n')
print ("Number of matches won by away team: ", awayWins)
print ("Win rate of away team: ", awayRate)

Total number of matches:  6840
Number of features:  6 

Number of matches won by home team:  3176
Win rate of home team:  46.4327485380117 

Number of matches drawn:  1751
Draw rate of the total matches:  25.599415204678362 

Number of matches won by away team:  1913
Win rate of away team:  27.96783625730994


In [8]:
X_all= df.drop(['FTR'],1)
y_all= df['FTR']

In [9]:
from sklearn.cross_validation import train_test_split

# Shuffle and split the dataset into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, 
                                                    test_size = 700,
                                                    random_state = 7)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [10]:
X_train.shape[0]

6140

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import GradientBoostingClassifier

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [12]:
clfDT = DecisionTreeClassifier()
clfGNB = GaussianNB()
clfMLP = MLPClassifier()
clfKNN = KNeighborsClassifier()
clfSVC = LinearSVC()
clfGBC = GradientBoostingClassifier()

In [13]:
predDT = clfDT.fit(X_train,y_train).predict(X_test)
print("Accuracy=",accuracy_score(predDT,y_test))
matrixDT = confusion_matrix(y_test, predDT)
matrixDT

Accuracy= 0.4114285714285714


array([[ 88,  50,  72],
       [ 62,  44,  70],
       [ 71,  87, 156]], dtype=int64)

In [14]:
predGNB = clfGNB.fit(X_train,y_train).predict(X_test)
print("Accuracy=",accuracy_score(predGNB,y_test))
matrixGNB = confusion_matrix(y_test, predGNB)
matrixGNB

Accuracy= 0.4928571428571429


array([[ 88,  13, 109],
       [ 49,  10, 117],
       [ 51,  16, 247]], dtype=int64)

In [15]:
predMLP = clfMLP.fit(X_train,y_train).predict(X_test)
print("Accuracy=",accuracy_score(predMLP,y_test))
matrixMLP = confusion_matrix(y_test, predMLP)
matrixMLP

Accuracy= 0.5342857142857143


array([[112,   5,  93],
       [ 60,  11, 105],
       [ 53,  10, 251]], dtype=int64)

In [16]:
predKNN = clfKNN.fit(X_train,y_train).predict(X_test)
print("Accuracy=",accuracy_score(predKNN,y_test))
matrixKNN = confusion_matrix(y_test, predKNN)
matrixKNN

Accuracy= 0.4757142857142857


array([[111,  49,  50],
       [ 68,  42,  66],
       [ 71,  63, 180]], dtype=int64)

In [17]:
predSVC = clfSVC.fit(X_train,y_train).predict(X_test)
print("Accuracy=",accuracy_score(predSVC,y_test))
matrixSVC = confusion_matrix(y_test, predSVC)
matrixSVC

Accuracy= 0.52


array([[105,   0, 105],
       [ 51,   0, 125],
       [ 55,   0, 259]], dtype=int64)

In [18]:
predGBC = clfGBC.fit(X_train,y_train).predict(X_test)
print("Accuracy=",accuracy_score(predGBC,y_test))
matrixGBC = confusion_matrix(y_test, predGBC)
matrixGBC

Accuracy= 0.5257142857142857


array([[106,  12,  92],
       [ 61,  15, 100],
       [ 54,  13, 247]], dtype=int64)